#! /bin/bash

if [[ "$1" = '0' ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_USE_LINKER=gold -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;AVR;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = "1" ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Debug   -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_USE_LINKER=gold -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;AVR;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = '2' ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;AVR;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = "3" ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Debug   -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;AVR;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = '4' ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;LoongArch;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = "5" ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Debug   -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;" -DLLVM_TARGETS_TO_BUILD="X86;LoongArch;" -DLLVM_ENABLE_EXPENSIVE_CHECKS=On -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = '6' ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;lld;" -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU;RISCV;" -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi

if [[ "$1" = "7" ]]; then
  cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Debug   -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;lld;" -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU;RISCV;" -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_BINUTILS_INCDIR=/data/home/bennshi/gnu/binutils-gdb/include -DBENCHMARK_ENABLE_EXCEPTIONS=Off ../llvm
fi
